# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details


version: 2.1
# orbs:
  # codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: openmcworkshop/workshop
      working_directory: ~/repo
    parallelism: 4
    steps:
      - checkout
      - run:
          name: run tests
          command: 
            # python paramak/setup.py install
            pytest tests
            # circleci tests glob **/tests/*.py | circleci tests split --split-by=timings | xargs python -m pytest --reuse-db --cov-report term --cov-report html:htmlcov --cov-report xml --junitxml=test-reports/junit.xml
            # pytest tests -v --cov=neutronics_material_makergit  --cov-report term --cov-report html:htmlcov --cov-report xml --junitxml=test-reports/junit.xml
            # pytest --cov=paramak --cov-report=xml
            # mkdir -p /root/repo/test-reports
            # pip3 install coverage --user
            # pip3 install pytest-cov
            # pytest --cov=./
            # py.test --cov-report=xml --cov=paramak ./
            # py.test -v
            # cp coverage.xml /root/repo/test-reports
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          # destination: test-reports
      - run:
          name: install curl
          command:
            apt-get install curl
      - run: curl -s https://codecov.io/bash | bash
      # - codecov/upload:
          # file: {{ coverage_report_filepath }}
