# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details


version: 2.1
# orbs:
  # codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: ghcr.io/fusion-energy/neutronics-workshop:dependencies
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test task 1
          command: pytest -v -s tests/test_task.py --name ../tasks/task_01_*/*.ipynb
      - run:
          name: test task 2
          command: pytest -v -s tests/test_task.py --name ../tasks/task_02_*/*.ipynb
      - run:
          name: test task 3
          command: pytest -v -s tests/test_task.py --name ../tasks/task_03_*/*.ipynb
      - run:
          name: test task 4
          command: pytest -v -s tests/test_task.py --name ../tasks/task_04_*/*.ipynb
      - run:
          name: test task 5
          command: pytest -v -s tests/test_task.py --name ../tasks/task_05_*/*.ipynb
      - run:
          name: test task 6
          command: pytest -v -s tests/test_task.py --name ../tasks/task_06_*/*.ipynb
      - run:
          name: test task 7
          command: pytest -v -s tests/test_task.py --name ../tasks/task_07_*/*.ipynb
      - run:
          name: test task 8
          command: pytest -v -s tests/test_task.py --name ../tasks/task_08_*/*.ipynb
      - run:
          name: test task 9
          command: pytest -v -s tests/test_task.py --name ../tasks/task_09_*/*.ipynb
      - run:
          name: test task 10
          command: pytest -v -s tests/test_task.py --name ../tasks/task_10_*/*.ipynb
      - run:
          name: test task 11
          command: pytest -v -s tests/test_task.py --name ../tasks/task_11_*/*.ipynb
      - run:
          name: test task 12
          command: pytest -v -s tests/test_task.py --name ../tasks/task_12_*/*.ipynb
      - run:
          name: test task 13
          command: pytest -v -s tests/test_task.py --name ../tasks/task_13_*/*.ipynb
      - run:
          name: test task 14
          command: pytest -v -s tests/test_task.py --name ../tasks/task_14_*/*.ipynb
