name: CI
on:  
  pull_request:    
    branches:
    - main  
    - develop
  push:
    branches:
    - main
    - develop
jobs:  
  build:     
   runs-on: ubuntu-latest
   
   steps:    
   - uses: actions/checkout@v1
   - name: Build and test with Docker
     run: |
       docker build --tag openmc_docker --build-arg compile_cores=2 .
       docker run --rm openmc_docker pytest ../tests