# This yml file will trigger a Github Action on release creation.
# This Action will build and upload a Docker image to GHCR
# https://github.com/marketplace/actions/publish-docker

name: docker-publish-release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build_and_push_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: dependencies build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          target: dependencies
          tags: ghcr.io/fusion-energy/neutronics-workshop:dependencies
          build-args: |
            include_avx=false
            build_double_down=OFF
            compile_cores=2
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: base build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          target: base
          tags: ghcr.io/fusion-energy/neutronics-workshop:base
          build-args: |
            include_avx=false
            build_double_down=OFF
            compile_cores=2

      - name: default build and push Docker image
        uses: docker/build-push-action@v
        with:
          push: true
          tags: ghcr.io/fusion-energy/neutronics-workshop
          build-args: |
            include_avx=false
            build_double_down=OFF
            compile_cores=2

      - name: embree build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/fusion-energy/neutronics-workshop:embree
          build-args: |
            include_avx=false
            build_double_down=ON
            compile_cores=2

      - name: embree-avx build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/fusion-energy/neutronics-workshop:embree-avx
          build-args: |
            include_avx=true
            build_double_down=ON
            compile_cores=2
